export const CARGAR_EVENTOS = "CARGAR_EVENTOS";
export const CREAR_EVENTO = "CREAR_EVENTO";
export const ACTUALIZAR_EVENTO = "ACTUALIZAR_EVENTO";
export const BORRAR_EVENTO = "BORRAR_EVENTO";
export const AGREGAR_TIPOBOLETO_EVENTO = "AGREGAR_TIPOBOLETO_EVENTO";
export const ELIMINAR_TIPOBOLETO_EVENTO = "ELIMINAR_TIPOBOLETO_EVENTO";
